config/routes.rb
Formy::Application.routes.draw do
  resources :tickets

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  serialize :checkbox_results
  serialize :textbox_results
  attr_accessible :name, :problem, :checkbox_results, :textbox_results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController


  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])

  end

  # POST /tickets
  # POST /tickets.json
  def create

    @ticket = Ticket.new(params[:ticket])

    if params["ticket_checkboxes"]
      @ticket.checkbox_results = params["ticket_checkboxes"]
    end
    if params["ticket_textfields"]
      @ticket.textbox_results = params["ticket_textfields"]
    end

    respond_to do |format|

      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>

    <%= f.input :name %>

    <%= f.input :problem %>

    <% CHECKBOXES.each do |field| %>
        <p>
          <%= label_tag field %>
          <%= "<input type=\"checkbox\" name=\"ticket_checkboxes[#{field}]\" #{"checked=checked" if @ticket.checkbox_results.to_hash.from_keys(field).values == ["on"]}".html_safe %>
        </p>
    <% end %>

    <% TEXTFIELDS.each do |field| %>
        <p>
          <%= label_tag field %>
          <%= "<input type=\"text\" name=\"ticket_textfields[#{field}]\" value=\"#{ @ticket.textbox_results.to_hash.from_keys(field).values[0] }\"".html_safe %>
        </p>
    <% end %>

    <p>&nbsp;</p>
    <%= f.submit %>

<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Form Tester</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Problem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.name %></td>
    <td><%= ticket.problem %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ticket.name %>
</p>

<p>
  <b>Problem:</b>
  <%= @ticket.problem %>
</p>



<% @ticket.checkbox_results.keys.each do |field| %>
    <li><%= field %></li>
<% end %>

<table style="border: solid; border-bottom: solid; border-left: solid;">
  <thead>
  <tr>
    <% @ticket.textbox_results.keys.each do |field| %>
        <th style="border: solid; border-bottom: solid; border-left: solid;"><%= field %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <tr>
    <% @ticket.textbox_results.values.each do |field| %>
        <td><%= if field then field else "NA" end %></td>
    <% end %>
  </tr>
  </tbody>
</table>


<%# (@ticket.textbox_results.merge @ticket.checkbox_results).to_a %>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>